- src/com/intellij/idea/plugin/hybris/tools/remote/http/AbstractHybrisHacHttpClient.java
- src/com/intellij/idea/plugin/hybris/tools/remote/http/CookieParser.java
Signed-off-by: Oleksandr Mishchuk san4es.mc@gmail.com
> IIP-407: SSL Handshake fails when testing connection to HAC

- resources/i18n/HybrisBundle.properties
- src/com/intellij/idea/plugin/hybris/settings/HybrisApplicationSettingsForm.form
- src/com/intellij/idea/plugin/hybris/settings/HybrisApplicationSettingsForm.java
Signed-off-by: Oleksandr Mishchuk san4es.mc@gmail.com
> IIP-401: Remove leftovers of Hybris remote configuration from main settings window

- src/com/intellij/idea/plugin/hybris/flexibleSearch/completion/provider/FSFieldsCompletionProvider.kt
- src/com/intellij/idea/plugin/hybris/tools/remote/console/view/HybrisConsolePanel.kt
Signed-off-by: Nosov Aleksandr nosovae.dev@gmail.com
> IIP-420 Typo in Hybris Console - tab "Groovy Scriptiong"

- resources/i18n/HybrisBundle.properties
- src/com/intellij/idea/plugin/hybris/tools/remote/http/AbstractHybrisHacHttpClient.java
- src/com/intellij/idea/plugin/hybris/toolwindow/HybrisToolWindow.java
> IIPS-152 added error message

- src/com/intellij/idea/plugin/hybris/type/system/meta/impl/TSMetaModelAccessImpl.java
> IIP-459 preventing error: Wrong dependency type: class java.util.HashSet

- common/src/com/intellij/idea/plugin/hybris/common/HybrisConstants.java
- src/com/intellij/idea/plugin/hybris/project/configurators/impl/DefaultLibRootsConfigurator.java
- src/com/intellij/idea/plugin/hybris/project/descriptors/AbstractHybrisModuleDescriptor.java
- src/com/intellij/idea/plugin/hybris/project/descriptors/DefaultJavaLibraryDescriptor.java
- src/com/intellij/idea/plugin/hybris/project/descriptors/HybrisModuleDescriptor.java
- src/com/intellij/idea/plugin/hybris/project/descriptors/RegularHybrisModuleDescriptor.java
- src/com/intellij/idea/plugin/hybris/project/tasks/ImportProjectProgressModalWindow.java
> IIP-378 register *server.jar as a separate library

- src/com/intellij/idea/plugin/hybris/project/configurators/GradleConfigurator.java
- src/com/intellij/idea/plugin/hybris/project/configurators/impl/DefaultEclipseConfigurator.java
- src/com/intellij/idea/plugin/hybris/project/configurators/impl/DefaultGradleConfigurator.java
- src/com/intellij/idea/plugin/hybris/project/configurators/impl/DefaultMavenConfigurator.java
- src/com/intellij/idea/plugin/hybris/project/descriptors/GradleModuleDescriptor.java
- src/com/intellij/idea/plugin/hybris/project/tasks/ImportProjectProgressModalWindow.java
- src/com/intellij/idea/plugin/hybris/project/utils/ModuleGroupUtils.java
allow all external modules to be grouped by hybris4intellij.properties
> IIP-464 allow all external modules to be custom grouped

- gradle.properties
- src/com/intellij/idea/plugin/hybris/impex/folding/ImpexPropertyFoldingBuilder.kt
- src/com/intellij/idea/plugin/hybris/impex/inspection/analyzer/ImpexModificationValueAnalyzer.kt
Signed-off-by: Aleksandr Nosov nosovae.dev@gmail.com
> IIP-460 Impex: invalid override validation. 

- src/com/intellij/idea/plugin/hybris/settings/HybrisApplicationSettingsForm.java
Signed-off-by: Your Real Name your.email@email.com
> IIPS-172 fixed doubled property resolve

- gradle.properties
Signed-off-by: Aleksandr Nosov nosovae.dev@gmail.com@email.com
> update Kotlin version to 1.2.70

- common/src/com/intellij/idea/plugin/hybris/common/HybrisConstants.java
- src/com/intellij/idea/plugin/hybris/project/tasks/ImportProjectProgressModalWindow.java
> IIP-473 provide a basic dictionary for hybris projects

- gradle.properties
Signed-off-by: Evgenii Kudelevskii ekudel@gmail.com
> IIP-410 Add plugin dependencies to the list to make tests working

- src/com/intellij/idea/plugin/hybris/project/tasks/ImportProjectProgressModalWindow.java
- src/com/intellij/idea/plugin/hybris/settings/HybrisDeveloperSpecificProjectSettingsListener.java
- src/com/intellij/idea/plugin/hybris/toolwindow/HybrisToolWindow.java
>  IIP-474 clear tool window when a new window is created

- common/src/com/intellij/idea/plugin/hybris/common/HybrisConstants.java
Signed-off-by: Your Real Name your.email@email.com
> IIP-473 add impex

- src/com/intellij/idea/plugin/hybris/type/system/meta/impl/TSMetaClassImpl.java
Signed-off-by: Aleksandr Nosov nosovae.dev@gmail.com
> IIP-478 unknown attribute in impex from super classes.

- src/com/intellij/idea/plugin/hybris/project/tasks/ImportProjectProgressModalWindow.java
- src/com/intellij/idea/plugin/hybris/settings/HybrisDeveloperSpecificProjectSettings.java
- src/com/intellij/idea/plugin/hybris/settings/HybrisDeveloperSpecificProjectSettingsComponent.java
- src/com/intellij/idea/plugin/hybris/settings/HybrisRemoteConnectionSettings.java
- src/com/intellij/idea/plugin/hybris/tools/remote/console/actions/handler/HybrisChooseInstanceAction.kt
> IIP-493 introduce more reliable ID for remote connection settings

- src/com/intellij/idea/plugin/hybris/project/wizard/CheckRequiredPluginsStep.java
- src/com/intellij/idea/plugin/hybris/project/wizard/SelectHybrisModulesToImportStep.java
> IIPS-176 add database as ultimate plugin

- resources/i18n/HybrisBundle.properties
- src/com/intellij/idea/plugin/hybris/tools/remote/action/ImportImpexAction.java
- src/com/intellij/idea/plugin/hybris/tools/remote/action/ValidateImpexAction.java
- src/com/intellij/idea/plugin/hybris/tools/remote/console/actions/handler/HybrisConsoleExecuteActionHandler.kt
> IIP-492 autodetect FS parameters

- src/com/intellij/idea/plugin/hybris/type/system/meta/impl/TSMetaModelImpl.java
Signed-off-by: Your Real Name your.email@email.com
> IIPS-181 NPE fix

- src/com/intellij/idea/plugin/hybris/linemaker/HybrisPopulatorLineMakerProvider.kt
Signed-off-by: Nosov Aleksandr nosovae.dev@gmail.com
> IIP-514 NullPointerException in HybrisPopulatorLineMakerProvider

- src/com/intellij/idea/plugin/hybris/project/tasks/ImportProjectProgressModalWindow.java
- src/com/intellij/idea/plugin/hybris/toolwindow/HybrisToolWindow.java
Signed-off-by: Aleksandr Nosov nosovae.dev@gmail.com
> IIP-516 NPE during save or load a solr connection config.

- src/com/intellij/idea/plugin/hybris/linemaker/HybrisPopulatorLineMakerProvider.kt
Signed-off-by: Aleksandr Nosov nosovae.dev@gmail.com
Added sorting for suggest result
> IIP-509 with sorting results. 

- src/com/intellij/idea/plugin/hybris/project/descriptors/DefaultHybrisProjectDescriptor.java
- src/com/intellij/idea/plugin/hybris/project/utils/FileUtils.java
> IIP-512 symlinks are expanded for module comparison only

- common/src/com/intellij/idea/plugin/hybris/common/HybrisConstants.java
- resources/i18n/HybrisBundle.properties
- src/com/intellij/idea/plugin/hybris/project/configurators/impl/ReadOnlyContentRootConfigurator.java
- src/com/intellij/idea/plugin/hybris/project/configurators/impl/RegularContentRootConfigurator.java
- src/com/intellij/idea/plugin/hybris/settings/HybrisApplicationSettings.java
- src/com/intellij/idea/plugin/hybris/settings/HybrisApplicationSettingsForm.form
- src/com/intellij/idea/plugin/hybris/settings/HybrisApplicationSettingsForm.java
Signed-off-by: Fabian Necci fabian.necci@gmail.com
> IIP-524 configurable list of extensions for which the resources folder is excluded

- common/src/com/intellij/idea/plugin/hybris/common/HybrisConstants.java
- resources/i18n/HybrisBundle.properties
- src/com/intellij/idea/plugin/hybris/project/configurators/impl/ReadOnlyContentRootConfigurator.java
- src/com/intellij/idea/plugin/hybris/project/configurators/impl/RegularContentRootConfigurator.java
- src/com/intellij/idea/plugin/hybris/settings/HybrisApplicationSettings.java
- src/com/intellij/idea/plugin/hybris/settings/HybrisApplicationSettingsForm.form
- src/com/intellij/idea/plugin/hybris/settings/HybrisApplicationSettingsForm.java
> IIP-524 excluding resource directory of selected modules

- src/com/intellij/idea/plugin/hybris/completion/provider/ItemTypeCodeCompletionProvider.java
Signed-off-by: Evgenii Kudelevskii ekudel@gmail.com
> IIP-487: Allow completion of keywords too

- src/com/intellij/idea/plugin/hybris/psi/references/TypeSystemReferenceBase.java
Signed-off-by: Evgenii Kudelevskii ekudel@gmail.com
> IIP-489 Support passing range to reference explicitly

- resources/inspectionDescriptions/DuplicateBeanDefinitionInspection.html
- resources/inspectionDescriptions/NoUniqueValueInspection.html
- resources/inspectionDescriptions/UniqueDocumentId.html
- resources/inspectionDescriptions/UnknownConfigPropertyInspection.html
- resources/inspectionDescriptions/UnknownMacrosInspection.html
- resources/inspectionDescriptions/UnknownTypeAttributeInspection.html
> IIPS-198 added missing html for inspection description.

- resources/colorSchemes/ImpexDarcula.xml
- resources/colorSchemes/ImpexDefault.xml
> IIP-530 non red colour for document ID

- src/com/intellij/idea/plugin/hybris/impex/inspection/UnknownMacrosInspection.kt
> IIP-531 macro evaluation as a prefix

- common/src/com/intellij/idea/plugin/hybris/common/HybrisConstants.java
- src/com/intellij/idea/plugin/hybris/common/services/CommonIdeaService.java
- src/com/intellij/idea/plugin/hybris/common/services/impl/DefaultCommonIdeaService.java
- src/com/intellij/idea/plugin/hybris/project/configurators/impl/DefaultGroupModuleConfigurator.java
- src/com/intellij/idea/plugin/hybris/project/descriptors/RegularHybrisModuleDescriptor.java
- src/com/intellij/idea/plugin/hybris/project/services/impl/DefaultHybrisProjectService.java
- src/com/intellij/idea/plugin/hybris/type/system/inspections/TypeSystemValidationUtils.java
> IIP-536 allow bin/modules directory to be recognized as OOTB

- common/src/com/intellij/idea/plugin/hybris/common/HybrisConstants.java
- resources/META-INF/java-optional-dependencies.xml
- resources/i18n/HybrisBundle.properties
- src/com/intellij/idea/plugin/hybris/project/configurators/ConfiguratorFactory.java
- src/com/intellij/idea/plugin/hybris/project/configurators/HybrisConfiguratorCache.java
- src/com/intellij/idea/plugin/hybris/project/configurators/JavaCompilerConfigurator.java
- src/com/intellij/idea/plugin/hybris/project/configurators/RunConfigurationConfigurator.java
- src/com/intellij/idea/plugin/hybris/project/configurators/impl/DebugRunConfigurationConfigurator.java
- src/com/intellij/idea/plugin/hybris/project/configurators/impl/DefaultConfiguratorFactory.java
- src/com/intellij/idea/plugin/hybris/project/configurators/impl/DefaultJavaCompilerConfigurator.java
- src/com/intellij/idea/plugin/hybris/project/tasks/ImportProjectProgressModalWindow.java
Signed-off-by: Evgenii Kudelevskii ekudel@gmail.com
> IIP-488 Configure compiler according to "build.compiler" property

- src/com/intellij/idea/plugin/hybris/common/services/impl/DefaultCommonIdeaService.java
Signed-off-by: Fabian Necci fabian.necci@gmail.com
> IIPS-207 fix handling of 1811.x hybris version
